#!/bin/bash

oper=$1
inst=$2

if [ -z "$oper" -o -z "$inst" ]; then
    echo "usage: $(basename $0) [start|stop|status|restart|license] inst_seq"
    exit 1
fi

dir=$(dirname $(readlink -f $(which $0)))
ver=$(${dir}/inst-query -q inst_seq=${inst} inst_version)
versions_dir=$(echo "<?php require dirname('$dir').'/config/install_params.php'; echo \$versions_dir; " | php)

if [ -z "$ver" ]; then
    echo "Instance $inst was not found or has no version assigned."
    echo "Devel computer and wrong product_code? (try export product_code=NTP|VPND|WTM)"
    exit 1
fi

ctl=${versions_dir}/${ver}/util/ctl.initd

if [ "${oper}" = "license" ]; then
    lic_ctl="${versions_dir}/${ver}/bin/lic_ctl -w /home/instances/${inst}/var/winco/regdb/"

    lic=$(${lic_ctl}  -f list_licenses | awk '/License:/ { print $2}')

    sudo -u \#${inst} ${lic_ctl} del_license ${lic}
    [ "$3" != "" ] && lic=$3
    sudo -u \#${inst} ${lic_ctl} add_license ${lic}    
    exit
fi

${ctl} ${oper} ${inst}

exit 0