#!/usr/bin/php
<?php

require_once dirname(__DIR__)."/common/wcf.php";

if ($argc < 2) {
	echo "usage: ".basename($argv['0'])." [-a] [-q p=val ..] [ pname ... ]\n";
	exit(1);
}

$instances = new $instance_classname;

$program_name = array_shift($argv);

while (@$argv[0]{0} == '-') {
    switch ($argv[0]) {
    case '-a':
        break;
    case '-q':
        if (empty($argv[1]))
            die("Missing argument for {$argv[0]}: Type {$program_name} without arguments for help.\n");
        $k = strtok($argv[1], '=');
        $v = strtok('');
        if (empty($k) || $v === false)
            die("Wrong argument for {$argv[0]}: Type {$program_name} without arguments for help.\n");
        $instances->{$k} = $v;
        array_shift($argv);
        break;
    default:
        die("{$argv[0]}: invalid argument. Type {$program_name} without arguments for help.\n");
    }
    array_shift($argv);
}

if (!$instances->select(getDbConn()))
    exit;

while (!empty($argv[0])) {
    $output_cols[] = $argv[0];
    array_shift($argv);
}

if (empty($output_cols))
    $output_cols = array('inst_seq', 'inst_id');


while ($instances->fetch()) {
    $space = false;
    foreach ($output_cols as $col) {
        if ($space)
            echo "\t";
        $space = true;
        echo $instances->{$col};
    }
    echo "\n";
}