#!/bin/sh

RUNNAME=`basename $0`

if [ "$1" == "start" ]; then
	if [ -e /var/run/$RUNNAME.pid ]; then
		if [ -e /proc/`cat /var/run/$RUNNAME.pid`/exe ]; then
			echo $0 already started
			exit 1
		fi
	fi
	nohup $0 daemon > /var/log/$RUNNAME.log 2>&1 &
	exit 0
fi

if [ "$1" == "stop" ]; then
	if [ -e /var/run/$RUNNAME.pid ]; then
		SPID=`cat /var/run/$RUNNAME.pid`
		if [ $SPID -gt 1 ]; then
			echo killing  $SPID `ps --ppid $SPID --no-headers -o pid`
			kill -9 $SPID `ps --ppid $SPID --no-headers -o pid`
			rm /var/run/$RUNNAME.pid
		fi
	else
		echo $0 not found on the system
	fi
	exit 0
fi

if [ "$1" == "restart" ]; then
	$0 stop
	$0 start
	exit 0
fi

if [ "$1" == "daemon" ]; then
	echo $$ > /var/run/$RUNNAME.pid

	tail -F /var/log/new_instances.log | (
        	while true; do
                	read ID
					if [ -f /etc/init.d/wc7-$ID ]; then
						/etc/init.d/wc7-$ID start
					elif [ -f /etc/init.d/wtm-$ID ]; then
						/etc/init.d/wtm-$ID start
					elif [ -f /etc/init.d/ntp-$ID ]; then
						/etc/init.d/ntp-$ID start
					elif [ -f /etc/init.d/vpnd-$ID ]; then
						/etc/init.d/vpnd-$ID start
					fi
        	done
	)
fi

if [ -e /proc/`cat /var/run/$RUNNAME.pid`/exe ]; then
	SPID=`cat /var/run/$RUNNAME.pid`
	echo $SPID `ps --ppid $SPID --no-headers -o pid`
else
	echo $0 daemon is not running
fi
